<?php

namespace Database\Seeders;

use App\Enums\PublicationStatus;
use App\Models\ProjectComponent;
use Illuminate\Database\Seeder;

/**
 * The four official SPIN project components.
 *
 * Names and descriptions come from the SPIN Project Website Development
 * Information Collection Form — nothing here is invented, and no additional
 * components are created.
 *
 * The component text is the supplied description; the collection form does
 * not supply per-component objectives or activities, so none are seeded —
 * the pages show content-ready empty states until the CMS adds them. The
 * records are seeded as PUBLISHED: this is the official project information
 * already on the public site's source document, and the CMS can unpublish or
 * edit each component at any time.
 */
class ProjectComponentSeeder extends Seeder
{
    public function run(): void
    {
        $components = [
            [
                'slug' => 'institutional-strengthening-and-capacity-building',
                'name' => 'Institutional Strengthening and Capacity Building for Water Resources Management',
                'short_name' => 'Institutional Strengthening & Capacity Building',
                'summary' => 'Strengthening the institutions, practices and capacity needed to plan, operate and manage water resources infrastructure.',
                'description' => 'This component improves the business and sector practices of federal and state implementing agencies '
                    .'to plan for hydropower development, project modelling and financing strategies, and supports state legislation '
                    .'and state budget line adoption for Water Users Associations to support farmers. It also promotes safer operation '
                    .'of dams by dam owners and operators through Dam Safety Guidelines approved and adopted by the Federal Steering '
                    .'Committee, using hydrological information generated by the hydro-meteorological stations and irrigation management '
                    .'systems under the project for water allocations.',
            ],
            [
                'slug' => 'irrigation-modernization',
                'name' => 'Irrigation Modernization',
                'short_name' => 'Irrigation Modernization',
                'summary' => 'Rehabilitating and revitalizing irrigated command areas through modernized irrigation and drainage infrastructure alongside policy and regulatory reform.',
                'description' => 'This component supports the rehabilitation and revitalization of 40,000 ha of irrigated command area through '
                    .'a comprehensive modernization programme that combines improved irrigation and drainage infrastructure with the '
                    .'implementation of policy, institutional and regulatory reforms.',
            ],
            [
                'slug' => 'dam-operations-and-dam-safety',
                'name' => 'Improvements in Dam Operations and Enhancing Dam Safety',
                'short_name' => 'Dam Operations & Safety',
                'summary' => 'Improving dam operations and dam safety measures so that dams operate with climate-resilient procedures.',
                'description' => 'Dams with improved and climate-resilient operational procedures and dam safety measures under the SPIN Project '
                    .'are more effective. Dam rehabilitation priorities analysis is completed based on Dam Safety Portfolio Risk Management '
                    .'Analysis results, and more people benefit from climate-resilient infrastructure.',
            ],
            [
                'slug' => 'project-management',
                'name' => 'Project Management',
                'short_name' => 'Project Management',
                'summary' => 'Effective implementation, monitoring and evaluation of project activities.',
                'description' => 'The main objective of this component is to effectively implement, monitor and evaluate project activities, '
                    .'including the registration and resolution of grievances through the Grievance Redress Mechanism and the satisfaction '
                    .'of farmer beneficiaries with irrigation services.',
            ],
        ];

        foreach ($components as $index => $component) {
            ProjectComponent::query()->updateOrCreate(
                ['slug' => $component['slug']],
                [
                    ...$component,
                    'status' => PublicationStatus::Published,
                    'published_at' => now(),
                    'sort' => $index + 1,
                ],
            );
        }
    }
}
