<?php

namespace App\Support;

use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

/**
 * Managed image storage — the single mechanism behind every administrator
 * image upload (admin News/Event "Cover Photo" fields, Media-phase photo
 * uploads and gallery covers).
 *
 * Images live on the existing `public` disk under type-specific managed
 * folders (`news/covers/…`, `events/covers/…`, `photos/…`,
 * `galleries/covers/…`), mirroring the project's existing top-level storage
 * layout (`documents/…`). Filenames are generated by the filesystem
 * (collision-safe, no user filenames), and the database stores the path
 * relative to the disk root — the same reference style every other table
 * uses — which the public resources resolve through `asset('storage/…')`.
 *
 * Deletion is deliberately conservative: only paths inside the managed
 * folders are ever removed, so a stray value in an image column that points
 * elsewhere can never be destroyed by this workflow.
 */
final class CoverImage
{
    /** Managed folders, by content type. */
    public const FOLDERS = [
        'news' => 'news/covers',
        'events' => 'events/covers',
        'galleries' => 'galleries/covers',
        'photos' => 'photos',
    ];

    /** Store an uploaded cover image; returns the disk-relative path. */
    public static function store(string $type, UploadedFile $file): string
    {
        $folder = self::FOLDERS[$type] ?? throw new \InvalidArgumentException("Unknown cover-image type [{$type}].");

        return (string) $file->store($folder, 'public');
    }

    /**
     * Delete a stored cover image — but only if it lives in a managed
     * folder. Anything else is left untouched.
     */
    public static function deleteManaged(?string $path): void
    {
        if ($path === null || $path === '') {
            return;
        }

        foreach (self::FOLDERS as $folder) {
            if (str_starts_with($path, $folder.'/')) {
                Storage::disk('public')->delete($path);

                return;
            }
        }
    }

    /**
     * Public URL for a stored cover image — null when no path is set or the
     * file no longer exists, so the UI renders its designed placeholder
     * rather than a broken image (the TeamMemberResource convention).
     */
    public static function url(?string $path): ?string
    {
        if ($path === null || $path === '') {
            return null;
        }

        return Storage::disk('public')->exists($path)
            ? asset('storage/'.$path)
            : null;
    }
}
