<?php

namespace App\Support;

use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

/**
 * Managed document storage — the single mechanism behind every administrator
 * document upload, mirroring CoverImage's conservative rules for the
 * `documents/` folder (the project's existing top-level storage layout).
 *
 * Filenames are generated by the filesystem (collision-safe, no user
 * filenames), and the database stores the path relative to the disk root —
 * the reference style every other table uses. Public access never links the
 * stored path directly: downloads stream through DocumentDownloadController.
 *
 * Deletion is deliberately conservative: only paths inside the managed
 * `documents/` folder are ever removed, so a stray value that points
 * elsewhere can never be destroyed by this workflow.
 */
final class DocumentFile
{
    /** The managed folder, relative to the public disk root. */
    public const FOLDER = 'documents';

    /** Store an uploaded document; returns the disk-relative path. */
    public static function store(UploadedFile $file): string
    {
        return (string) $file->store(self::FOLDER, 'public');
    }

    /**
     * Delete a stored document — but only if it lives in the managed
     * folder. Anything else (external path, already-removed file) is left
     * untouched.
     */
    public static function deleteManaged(?string $path): void
    {
        if ($path === null || $path === '') {
            return;
        }

        if (str_starts_with($path, self::FOLDER.'/')) {
            Storage::disk('public')->delete($path);
        }
    }

    /** Resolved public download URL for the admin screens — null when unset. */
    public static function url(?int $id): ?string
    {
        return $id !== null ? route('resources.download', ['document' => $id]) : null;
    }
}
